spring:
  datasource:
    url: jdbc:postgresql://localhost:5472/rag-project-vectordb
    username: rag-project
    password: 12341234
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1536
        initialize-schema: true
        schema-validation: true