version: '3.8'
# docker-compose -f docker/local/docker-compose.local.yml -p myeonjeobjjang-local up -d

services:
  pgvector:
    container_name: pgvector-myeonjeobjjang
    image: pgvector/pgvector:0.8.0-pg17
    ports:
      - 127.0.0.1:5472:5432
    environment:
      - POSTGRES_DB=rag-project-vectordb
      - POSTGRES_USER=rag-project
      - POSTGRES_PASSWORD=12341234
    networks:
      myeonjeobjjang-network:
        ipv4_address: 172.31.3.1
networks:
  myeonjeobjjang-network:
    name: myeonjeobjjang-network-local
    driver: bridge
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
          ip_range: 172.31.3.0/24
          gateway: 172.31.3.254