pipeline {
	agent any

    environment {
		REGISTRY = 'ghcr.io'
        REPOSITORY = 'myeonjeobjjang/backend'
        GITHUB_ACTOR = credentials('GITHUB_ACTOR')
        GITHUB_REGISTRY_TOKEN = credentials('GITHUB_REGISTRY_TOKEN')
        SSH_HOST = credentials('MJJ_BACKEND_SSH_HOST')
        SSH_PORT = credentials('MJJ_BACKEND_SSH_PORT')
        SSH_USER = credentials('MJJ_BACKEND_SSH_USER')
        SSH_PASS = credentials('MJJ_BACKEND_SSH_PASS')
    }

    tools {
		gradle 'gradle'
    }

    stages {
		stage('Git Checkout') {
			steps {
				git branch: 'develop', url: "https://github.com/${REPOSITORY}.git"
            }
        }

        stage('Build') {
			steps {
				sh '''
				cd ./myeonjeobjjang-boot/myeonjeobjjang-boot-api
				../../gradlew clean build -x test
				'''
            }
        }

        stage('Test') {
			steps {
				sh '''
				cd ./myeonjeobjjang-boot/myeonjeobjjang-boot-api
				../../gradlew test
				'''
            }
        }

		stage('Get Version') {
			steps {
				script {
					env.VERSION = sh(script: "git describe --tags || echo 'latest'", returnStdout: true).trim()
				}
			}
		}

        stage('Build and Push Image') {
			steps {
				sh '''
                docker build --no-cache -t ${REGISTRY}/${REPOSITORY}-onprem:${VERSION} -f docker/onprem/Dockerfile ./myeonjeobjjang-boot/myeonjeobjjang-boot-api
                echo ${GITHUB_REGISTRY_TOKEN} | docker login ${REGISTRY} -u ${GITHUB_ACTOR} --password-stdin
                docker push ${REGISTRY}/${REPOSITORY}-onprem:${VERSION}
                '''
            }
        }

        stage('Write Docker Image Tag Information to .env File') {
			steps {
				sh '''
                cd docker/onprem
				echo "\nSPRING_IMAGE=${REGISTRY}/${REPOSITORY}-onprem:${VERSION}" >> onprem.env
                '''
            }
        }

        stage('Copy docker-compose.yml and env to Server') {
			steps {
				// sshpass로 아이디/비밀번호 방식 scp 사용
                sh '''
                cd docker/onprem
                sshpass -p $SSH_PASS scp -P $SSH_PORT -o StrictHostKeyChecking=no docker-compose.yaml onprem.env $SSH_USER@$SSH_HOST:/home/mjj-back
                '''
            }
        }

        stage('Deploy') {
			steps {
				sh '''
				sshpass -p $SSH_PASS ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd /home/mjj-back; \
				docker login ${REGISTRY} -u ${GITHUB_ACTOR} -p ${GITHUB_REGISTRY_TOKEN}; \
				docker container stop spring || true; \
				docker container rm spring || true; \
				docker image rm ${REGISTRY}/${REPOSITORY}-onprem:${VERSION} || true; \
				docker-compose --env-file=onprem.env -f docker-compose.yaml -p backend up -d; \
				docker image prune -af || true;
				"
				'''
            }
        }
    }
}
