spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5472/rag-project-vectordb
    username: rag-project
    password: 12341234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true